name: 'Hello World ActionSmart334455'
description: 'A simple action that prints Hello World'
author: 'Praveen'
inputs:
  who-to-greet: 
    description: 'The name of the person to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'smile'
  color: 'blue'

